# Generated by Django 5.2.1 on 2025-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, help_text="Hex color code for the user's avatar background, e.g., #RRGGBB.", max_length=7),
        ),
    ] 