# Generated by Django 5.2.3 on 2025-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_city_user_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
