# Generated by Django 5.2.3 on 2025-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_current_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
