# Generated by Django 5.2.3 on 2025-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_orders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_manager_email',
            field=models.EmailField(blank=True, help_text='Email for delivery manager to receive order notifications.', max_length=254, null=True),
        ),
    ]
