# Generated by Django 5.2.3 on 2025-06-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar_color_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delivery_manager_email',
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery_manager',
            field=models.BooleanField(default=False, help_text='If true, this user will receive order notifications and PDFs.'),
        ),
    ]
