# Generated by Django 5.2.3 on 2025-06-23 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productphoto_productreview_websitereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='reviews.productreview'),
        ),
    ]
