# Generated by Django 5.2.4 on 2025-07-04 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('use_once_per_user', models.BooleanField(default=False, help_text='Voucher can be used only once per user')),
                ('require_previous_order', models.BooleanField(default=False, help_text='User must have completed at least one order')),
                ('categories', models.ManyToManyField(blank=True, help_text='Select categories this voucher applies to (leave empty for all categories)', to='products.category')),
            ],
        ),
    ]
