# Generated by Django 5.2.3 on 2025-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of allowed categories (e.g. tshirts,basictop)', max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='require_previous_order',
            field=models.BooleanField(default=False, help_text='User must have completed at least one order'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='use_once_per_user',
            field=models.BooleanField(default=False, help_text='Voucher can be used only once per user'),
        ),
    ]
