"""
Django settings for shortcut project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b^lazyv&dao&g79==@g#(m-ekmq6!pfmonptv8205opyqnu$3@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.1.4:8000',
    'http://192.168.1.4:5173',
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://192.168.1.4:8000",
    "http://192.168.1.4:5173",
]
CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    'nested_admin',
    'landing',
    'accounts.apps.AccountsConfig',
    'products',
    'cart',
    'orders',
    'reviews',
    'vouchers',
    'wishlist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'debug_toolbar',
    # 2FA apps
    'django_otp',
    'django_otp.plugins.otp_email',
    # 'two_factor',  # Disabled to allow admin login without 2FA
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'shortcut.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shortcut.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # Ensure custom admin icon CSS is included
    # 'static/admin/css/custom_admin_icons.css',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CORS settings duplicated below; keeping only the more specific allow list.
# CORS_ALLOW_ALL_ORIGINS = True  # Removed duplicate

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

# ===================================
# EMAIL CONFIGURATION
# ===================================

# Email backend configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shortcut756@gmail.com'
EMAIL_HOST_PASSWORD = 'wijpdbtlxdfseuxq'  # App password, no spaces

# Default email settings
DEFAULT_FROM_EMAIL = 'shortcut756@gmail.com'

# Django Sites Framework
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Social account settings
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Google OAuth settings (to be configured)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# ===================================
# AUTHENTICATION SETTINGS
# ===================================

# Login/Logout URLs
LOGIN_URL = '/admin-pZybk7TH5r8iNHvj/login/'
LOGOUT_REDIRECT_URL = '/'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ===================================
# SECURITY SETTINGS
# ===================================

# CSRF settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Session security
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Rate limiting (for future implementation)
# You can add django-ratelimit or similar packages for rate limiting

# Custom admin creation command
ADMIN_CREATION_COMMAND = """
from accounts.models import User
if not User.objects.filter(email='admin@example.com').exists():
    User.objects.create_superuser(
        email='admin@example.com',
        password='adminpassword',
        is_active=True  # Ensure admin is active
    )
"""

# ===================================
# DJANGO REST FRAMEWORK SETTINGS
# ===================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Allow any by default, individual views can override with more restrictive permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

# ===================================
# CORS SETTINGS
# ===================================

# CORS settings for development
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Add Unfold settings for light mode with emerald green accent and dark mode
UNFOLD = {
    "SITE_TITLE": "Shortcut Store Admin",
    "SITE_HEADER": "Shortcut Store",
    "SITE_ICON": {
        "light": lambda request: static("images/favicon.ico"),
        "dark": lambda request: static("images/favicon.ico"),
    },
    "SITE_LOGO": {
        "light": lambda request: "/media/site-logo.svg",
        "dark": lambda request: "/media/site-logo.svg",
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",  # Force global dark mode
    "STYLES": [
        lambda request: static("admin/css/unfold-dark-global.css"),
    ],
    "COLORS": {
        "base": {
            "50": "250, 250, 250",
            "100": "244, 244, 245",
            "200": "228, 228, 231",
            "300": "161, 161, 170",
            "400": "113, 113, 122",
            "500": "82, 82, 91",
            "600": "63, 63, 70",    # Main background (dark gray)
            "700": "39, 39, 42",    # Deeper gray for sidebar/cards
            "800": "24, 24, 27",    # Even deeper, but not black
            "900": "17, 17, 20",    # For contrast/depth
            "950": "10, 10, 12",
        },
        "primary": {
            "50": "236, 253, 245",
            "100": "209, 250, 229",
            "200": "167, 243, 208",
            "300": "110, 231, 183",
            "400": "52, 211, 153",
            "500": "16, 185, 129",   # Emerald
            "600": "5, 150, 105",    # Dark emerald
            "700": "4, 120, 87",     # Army green
            "800": "6, 95, 70",
            "900": "6, 78, 59",
            "950": "2, 44, 34",
        },
        "font": {
            "subtle-dark": "161, 161, 170",    # gray-400
            "default-dark": "228, 228, 231",   # gray-200
            "important-dark": "255, 255, 255", # white
        },
    },
    "SIDEBAR": {
        "navigation": [
            {
                "label": "Store",
                "icon": "storefront",
                "items": [
                    {"model": "products.Product"},
                    {"model": "products.ProductVariant"},
                    {"model": "products.ProductColorVariant"},
                    {"model": "products.ProductStock"},
                    {"model": "orders.Order"},
                    {"model": "cart.Cart"},
                    {"model": "wishlist.Wishlist"},
                ],
            },
            {
                "label": "Users",
                "icon": "person",
                "items": [
                    {"model": "accounts.User"},
                ],
            },
            {
                "label": "Vouchers",
                "icon": "confirmation_number",
                "items": [
                    {"model": "vouchers.Voucher"},
                ],
            },
            {
                "label": "Reviews",
                "icon": "star",
                "items": [
                    {"model": "reviews.ProductReview"},
                    {"model": "reviews.WebsiteReview"},
                ],
            },
        ],
        "show_all_applications": True,
        "show_search": True,
    },
    "ENVIRONMENT_LABEL": "Production",  # Change as needed
}

# Two-Factor Auth (2FA) settings
TWO_FACTOR_EMAIL_GATEWAY = 'two_factor.gateways.email.EmailGateway'
TWO_FACTOR_EMAIL_SUBJECT = 'Your Shortcut Store Admin Login Code'
TWO_FACTOR_EMAIL_BODY_TEMPLATE = 'Your verification code is: {{ token }}\n\nIf you did not request this, please ignore this email.'
TWO_FACTOR_EMAIL_HTML_BODY_TEMPLATE = '<p>Your verification code is: <b>{{ token }}</b></p><p>If you did not request this, please ignore this email.</p>'
TWO_FACTOR_LOGIN_TIMEOUT = 300  # 5 minutes

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
