# Generated by Django 5.2.4 on 2025-07-04 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Descriptive title for the collection', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for this collection (used in hero section)', null=True, upload_to='collections/main/')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this collection')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this category')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='products_ca_name_752bb1_idx'), models.Index(fields=['slug', 'is_active'], name='products_ca_slug_269ba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for this category card', upload_to='category_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Image',
                'verbose_name_plural': 'Category Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image for this collection', upload_to='collections/gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.collectionimage')),
            ],
            options={
                'verbose_name': 'Collection Gallery Image',
                'verbose_name_plural': 'Collection Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('sale_percent', models.PositiveIntegerField(blank=True, db_index=True, help_text='Admin-only field: discount percent (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('indoor_image', models.ImageField(blank=True, help_text='Indoor image for product card (main image)', null=True, upload_to='products/indoor/')),
                ('outdoor_image', models.ImageField(blank=True, help_text='Outdoor/hover image for product card', null=True, upload_to='products/outdoor/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'sale_percent'], name='products_pr_categor_afe7b6_idx'), models.Index(fields=['price', 'created_at'], name='products_pr_price_3f4df3_idx'), models.Index(fields=['category', 'price'], name='products_pr_categor_ad7451_idx'), models.Index(fields=['name', 'category'], name='products_pr_name_4f9742_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Navy', 'Navy'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Burgundy', 'Burgundy'), ('Violet', 'Violet'), ('Olive', 'Olive'), ('Iron Grey', 'Iron Grey'), ('Sierra Blue', 'Sierra Blue'), ('Carbon Grey', 'Carbon Grey'), ('Other', 'Other')], max_length=20)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code (e.g., #000000)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'ordering': ['color'],
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductColorVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='color_variant_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productcolorvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock for this size under this color')),
                ('is_active', models.BooleanField(default=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.productcolorvariant')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('color_variant', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Reserved for pending orders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsizevariant')),
            ],
            options={
                'ordering': ['size_variant__color_variant__color', 'size_variant__size'],
                'unique_together': {('product', 'size_variant')},
            },
        ),
    ]
