# Generated by Django 5.2.3 on 2025-06-22 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero section image', upload_to='collections/')),
                ('title', models.CharField(blank=True, help_text='Descriptive title for the image', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collection Image',
                'verbose_name_plural': 'Collection Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_percent', models.PositiveIntegerField(blank=True, help_text='Admin-only field: discount percent (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of products in stock')),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('tshirts', 'T-Shirts'), ('basictop', 'Basic Top'), ('shoes', 'Shoes'), ('bottoms', 'Bottoms'), ('sets', 'Sets'), ('shorts', 'Shorts'), ('sweatpants', 'Sweatpants')], default='tshirts', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Navy', 'Navy'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Burgundy', 'Burgundy'), ('Violet', 'Violet'), ('Olive', 'Olive'), ('Iron Grey', 'Iron Grey'), ('Sierra Blue', 'Sierra Blue'), ('Carbon Grey', 'Carbon Grey'), ('Other', 'Other')], max_length=20)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code (e.g., #000000)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'ordering': ['color'],
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock for this size under this color')),
                ('is_active', models.BooleanField(default=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.productcolorvariant')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('color_variant', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Reserved for pending orders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsizevariant')),
            ],
            options={
                'ordering': ['size_variant__color_variant__color', 'size_variant__size'],
                'unique_together': {('product', 'size_variant')},
            },
        ),
    ]
