# Generated by Django 5.2.4 on 2025-07-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_901cfc_idx',
            old_name='products_pr_categor_afe7b6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_47b724_idx',
            old_name='products_pr_categor_ad7451_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_name_08fd2e_idx',
            old_name='products_pr_name_4f9742_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
