# Generated by Django 5.2.1 on 2025-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma-separated colors (Black,White,Red,Blue,Green,Yellow,Other)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes (XS,S,M,L,XL,XXL)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of products in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
