# Generated by Django 5.2.3 on 2025-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_productcolorvariantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolorvariantimage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='productcolorvariantimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productcolorvariantimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirts', 'T-Shirts'), ('basictop', 'Basic Tops'), ('sets', 'Sets')], default='tshirts', max_length=32),
        ),
    ]
