# Generated by Django 5.2.3 on 2025-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outdoor_image',
            field=models.ImageField(blank=True, help_text='Outdoor/hover image for product card', null=True, upload_to='products/outdoor/'),
        ),
    ]
