# Generated by Django 5.2.4 on 2025-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_product_products_pr_slug_3edc0c_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
