# Generated by Django 5.2.4 on 2025-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
        migrations.AddField(
            model_name='collectiongalleryimage',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
        migrations.AddField(
            model_name='collectionimage',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='indoor_image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='outdoor_image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
        migrations.AddField(
            model_name='productcolorvariantimage',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated image variants (WebP/AVIF, multiple sizes)', null=True),
        ),
    ]
