# Generated by Django 5.2.3 on 2025-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_outdoor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='indoor_image',
            field=models.ImageField(blank=True, help_text='Indoor image for product card (main image)', null=True, upload_to='products/indoor/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('tshirts', 'T-Shirts'), ('basictop', 'Basic Tops'), ('shoes', 'Shoes'), ('sets', 'Sets')], max_length=50),
        ),
    ]
