# Generated by Django 5.2.1 on 2025-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_id_productvariantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
