# Generated by Django 5.2.3 on 2025-06-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_indoor_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.RemoveField(
            model_name='collectionimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable this collection'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='title',
            field=models.CharField(blank=True, help_text='Descriptive title for the collection', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CollectionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image for this collection', upload_to='collections/gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.collectionimage')),
            ],
            options={
                'verbose_name': 'Collection Gallery Image',
                'verbose_name_plural': 'Collection Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
