# Generated by Django 5.2.1 on 2025-06-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
