# Generated by Django 5.2.4 on 2025-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_image_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariant',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
