# Generated by Django 5.2.3 on 2025-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_collectionimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for this collection (used in hero section)', null=True, upload_to='collections/main/'),
        ),
    ]
