# Generated by Django 5.2.1 on 2025-06-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
