# Generated by Django 5.2.3 on 2025-06-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_collectionimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionimage',
            name='image',
        ),
    ]
