# Generated by Django 5.2.1 on 2025-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirts', 'T-Shirts'), ('basictop', 'Basic Top'), ('shoes', 'Shoes')], default='tshirts', max_length=32),
        ),
    ]
