# Generated by Django 5.2.4 on 2025-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSizeProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Multi Size Product',
                'verbose_name_plural': 'Multi Size Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='OneSizeProduct',
            fields=[
            ],
            options={
                'verbose_name': 'One Size Product',
                'verbose_name_plural': 'One Size Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='category',
            name='is_one_size',
            field=models.BooleanField(default=False, help_text='Check if this category is for one-size products only'),
        ),
    ]
