# Generated by Django 5.2.4 on 2025-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_multisizeproduct_onesizeproduct_category_is_one_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color_variant_images/'),
        ),
    ]
