# Generated by Django 5.2.1 on 2025-06-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock for this size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirts', 'T-Shirts'), ('basictop', 'Basic Top'), ('shoes', 'Shoes'), ('bottoms', 'Bottoms'), ('sets', 'Sets'), ('shorts', 'Shorts'), ('sweatpants', 'Sweatpants')], default='tshirts', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Navy', 'Navy'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Burgundy', 'Burgundy'), ('Violet', 'Violet'), ('Olive', 'Olive'), ('Iron Grey', 'Iron Grey'), ('Sierra Blue', 'Sierra Blue'), ('Carbon Grey', 'Carbon Grey'), ('Other', 'Other')], max_length=20)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code (e.g., #000000)', max_length=7)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock for this color variant')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'ordering': ['color'],
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductColorVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='color_variants/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for this color variant')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productcolorvariant')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='colors',
        ),
    ]
