# Generated by Django 5.2.1 on 2025-06-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Reserved for pending orders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolorvariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
            ],
            options={
                'ordering': ['color_variant__color', 'size'],
                'unique_together': {('product', 'color_variant', 'size')},
            },
        ),
    ]
