# Generated by Django 5.2.4 on 2025-07-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productcolorvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='image',
        ),
    ]
