# Generated by Django 5.2.1 on 2025-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero section image', upload_to='collections/')),
                ('title', models.CharField(blank=True, help_text='Descriptive title for the image', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collection Image',
                'verbose_name_plural': 'Collection Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
