# Generated by Django 5.2.4 on 2025-07-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productcolorvariant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolorvariant',
            options={'ordering': ['created_at']},
        ),
    ]
