# Generated by Django 5.2.1 on 2025-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_collectionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionImage',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to hide this product from the store'),
        ),
    ]
